import { ServiceArea, ServiceCategory, Task, UserProfile, TechnicianOfferedService } from './types';

export const INITIAL_USER: UserProfile = {
  id: 'user-mostafa',
  name: 'مصطفى عزت',
  phone: '01012345678',
  role: 'عميل',
  isOnline: true,
  rating: 5.0,
  reviewsCount: 3,
  balance: 350, // Egyptian Pounds
  fingerprintAuth: true,
  freeRequestsLeft: 3, // New client 3 free requests
  technicianPoints: 50, // 50 points
  reputationPoints: 120,
  city: 'القاهرة',
};

export const DEFAULT_TECHNICIAN_SERVICES: TechnicianOfferedService[] = [
  {
    id: 'ts-1',
    name: 'صيانة وتسليك السباكة وفحص التسريبات',
    category: 'السباكة والأدوات الصحية',
    categoryIcon: 'Wrench',
    basePrice: 150,
    isActive: true,
    description: 'كشف تسريبات المياه، تغيير القلوب التالفة، تسليك بالضغط، وضمان 30 يوماً.',
  },
  {
    id: 'ts-2',
    name: 'تركيب وصيانة خلاطات ومحابس مياه إيطالي/تركي',
    category: 'السباكة والأدوات الصحية',
    categoryIcon: 'Wrench',
    basePrice: 120,
    isActive: true,
    description: 'فك وتركيب أطقم الخلاطات، سيفونات الدفن، محابس الزاوية، وتوصيل الفلاتر.',
  },
  {
    id: 'ts-3',
    name: 'صيانة فورية وغسيل تكييفات شارب وكاريير',
    category: 'تكييف وتبريد',
    categoryIcon: 'Wind',
    basePrice: 200,
    isActive: true,
    description: 'غسيل بالضغط العالي، فحص شحنة الفريون R22/R410، وتنظيف مجرى الصرف.',
  },
  {
    id: 'ts-4',
    name: 'فحص القواطع الكهربائية والأحمال المنزلية',
    category: 'الكهرباء والإنارة',
    categoryIcon: 'Zap',
    basePrice: 130,
    isActive: true,
    description: 'فحص أسباب فصل القاطع الرئيسي، توزيع الأحمال، وتغيير مفاتيح شنايدر/فينوس.',
  },
  {
    id: 'ts-5',
    name: 'تركيب وتصليح كوالين وأقفال الأبواب المصفحة',
    category: 'النجارة والأبواب',
    categoryIcon: 'Hammer',
    basePrice: 140,
    isActive: false,
    description: 'تغيير قلب الكالون، تصليح السقاطة، وتعديل خلوص الأبواب الخشب والمصفحة.',
  },
];

export const INITIAL_USERS_DIRECTORY: UserProfile[] = [
  INITIAL_USER,
  {
    id: 'user-ahmed',
    name: 'أحمد حسني',
    phone: '01123456789',
    role: 'فني',
    isOnline: true,
    rating: 4.9,
    reviewsCount: 142,
    balance: 500,
    fingerprintAuth: false,
    freeRequestsLeft: 0,
    technicianPoints: 45,
    reputationPoints: 230,
    city: 'القاهرة',
    specialty: 'فني سباكة وأدوات صحية معتمد',
    isAvailableForWork: true,
    workingHours: {
      enabled: true,
      startTime: '09:00',
      endTime: '19:00',
      days: ['السبت', 'الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس'],
      autoToggleAvailability: true,
      notes: 'متاح للطلبات الطارئة والعادية بالمعادي وما حولها',
    },
  },
  {
    id: 'user-mahmoud',
    name: 'محمود طارق',
    phone: '01098765432',
    role: 'عميل',
    isOnline: true,
    rating: 5.0,
    reviewsCount: 8,
    balance: 150,
    fingerprintAuth: true,
    freeRequestsLeft: 2,
    technicianPoints: 0,
    reputationPoints: 110,
    city: 'الجيزة',
  },
  {
    id: 'user-ibrahim',
    name: 'إبراهيم خليل',
    phone: '01234567890',
    role: 'فني',
    isOnline: true,
    rating: 4.8,
    reviewsCount: 96,
    balance: 420,
    fingerprintAuth: false,
    freeRequestsLeft: 0,
    technicianPoints: 70,
    reputationPoints: 195,
    city: 'القاهرة الجديدة',
    specialty: 'كهربائي منازل وتكييف معتمد',
    isAvailableForWork: false,
    workingHours: {
      enabled: true,
      startTime: '10:00',
      endTime: '20:00',
      days: ['السبت', 'الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس'],
      autoToggleAvailability: true,
    },
  },
];

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: 'plumbing',
    name: 'السباكة والأدوات الصحية',
    icon: 'Wrench',
    description: 'إصلاح التسريبات، تركيب خلاطات، تسليك وتأسيس',
    basePrice: 120,
    badge: 'الأكثر طلباً',
    color: 'bg-blue-500',
  },
  {
    id: 'electricity',
    name: 'الكهرباء والإنارة',
    icon: 'Zap',
    description: 'صيانة القواطع، تركيب نجف، فحص الشورت والأعطال',
    basePrice: 130,
    badge: 'طوارئ 24/7',
    color: 'bg-amber-500',
  },
  {
    id: 'ac',
    name: 'تكييف وتبريد',
    icon: 'Wind',
    description: 'تنظيف وغسيل، شحن فريون، صيانة وفك وتركيب',
    basePrice: 200,
    badge: 'عرض خاص',
    color: 'bg-cyan-500',
  },
  {
    id: 'carpentry',
    name: 'النجارة والأبواب',
    icon: 'Hammer',
    description: 'تصليح كوالين، تركيب مطابخ وأثاث، صيانة شبابيك',
    basePrice: 140,
    color: 'bg-orange-500',
  },
  {
    id: 'appliances',
    name: 'صيانة الأجهزة المنزلية',
    icon: 'Cpu',
    description: 'غسالات، ثلاجات، بوتاجازات، سخانات، ميكروويف',
    basePrice: 150,
    color: 'bg-purple-500',
  },
  {
    id: 'cleaning',
    name: 'النظافة والتعقيم',
    icon: 'Sparkles',
    description: 'نظافة شاملة للشقق، غسيل سجاد وأنتريهات بالبخار',
    basePrice: 250,
    color: 'bg-emerald-500',
  },
  {
    id: 'painting',
    name: 'نقاشة ودهانات',
    icon: 'Paintbrush',
    description: 'دهان غرف، معالجة رطوبة، تركيب ورق حائط وتعتيق',
    basePrice: 300,
    color: 'bg-pink-500',
  },
  {
    id: 'moving',
    name: 'نقل ورفع العفش',
    icon: 'Truck',
    description: 'سيارات نقل مجهزة، عمالة مدربة، ونش رفع هيدروليكي',
    basePrice: 500,
    color: 'bg-indigo-500',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-101',
    title: 'صيانة تسريب مياه بخلاط الحمام الرئيسي',
    category: 'السباكة والأدوات الصحية',
    categoryIcon: 'Wrench',
    status: 'in_progress',
    description: 'يوجد تسريب مستمر تحت الحوض وخلاط الدش يحتاج إلى تغيير جلد أو قلب سيراميك جديد.',
    price: 180,
    createdAt: 'منذ ساعتين',
    scheduledTime: 'اليوم، بين 3:00 و 4:30 مساءً',
    location: {
      lat: 29.9602,
      lng: 31.2569,
      address: 'شارع النصر، المعادي الجديدة، القاهرة',
      city: 'القاهرة',
      district: 'المعادي',
      buildingNumber: '42',
      floor: '3',
      apartment: '12',
      landmark: 'بجوار بنك مصر',
    },
    technician: {
      id: 'tech-1',
      name: 'المهندس أحمد حسني',
      avatar: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150&auto=format&fit=crop&q=80',
      rating: 4.9,
      reviewsCount: 142,
      phone: '01123456789',
      specialty: 'فني سباكة معتمد',
      distanceKm: 1.8,
      isAvailableForWork: true,
      workingHours: {
        enabled: true,
        startTime: '09:00',
        endTime: '19:00',
        days: ['السبت', 'الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس'],
        autoToggleAvailability: true,
      },
    },
    offersCount: 4,
    isUrgent: false,
    clientName: 'مصطفى عزت',
    clientPhone: '01012345678',
  },
  {
    id: 'task-102',
    title: 'فحص وتنظيف تكييف شارب 2.25 حصان',
    category: 'تكييف وتبريد',
    categoryIcon: 'Wind',
    status: 'pending',
    description: 'التكييف يخرج هواء ضعيف ويحتاج غسيل الوحدة الداخلية وفحص ضغط الفريون.',
    price: 260,
    createdAt: 'منذ 4 ساعات',
    scheduledTime: 'غداً، الساعة 11:00 صباحاً',
    location: {
      lat: 30.0131,
      lng: 31.4293,
      address: 'شارع التسعين الشمالي، التجمع الخامس، القاهرة الجديدة',
      city: 'القاهرة الجديدة',
      district: 'التجمع الخامس',
      buildingNumber: '10',
      floor: '2',
      apartment: '4',
      landmark: 'خلف مول كونكورد بلازا',
    },
    offersCount: 3,
    isUrgent: true,
    clientName: 'محمود طارق',
    clientPhone: '01098765432',
  },
  {
    id: 'task-103',
    title: 'تركيب نجفة 8 لمبات وإصلاح مفتاح إنارة',
    category: 'الكهرباء والإنارة',
    categoryIcon: 'Zap',
    status: 'closed',
    description: 'تم تركيب النجفة بنجاح وتغيير مفتاح اللوحة الكهربائية المتضرر.',
    price: 150,
    createdAt: 'أمس، 5:30 مساءً',
    scheduledTime: 'أمس، 6:00 مساءً',
    location: {
      lat: 30.0561,
      lng: 31.3411,
      address: 'شارع عباس العقاد، مدينة نصر، القاهرة',
      city: 'القاهرة',
      district: 'مدينة نصر',
      buildingNumber: '75',
      floor: '5',
      apartment: '19',
    },
    clientName: 'مصطفى عزت',
    clientPhone: '01012345678',
    technician: {
      id: 'tech-2',
      name: 'محمود عبد الرحيم',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      rating: 4.8,
      reviewsCount: 88,
      phone: '01098765432',
      specialty: 'كهربائي منازل معتمد',
      distanceKm: 3.2,
    },
    offersCount: 5,
  },
  {
    id: 'task-104',
    title: 'عطل طارئ: انقطاع الكهرباء وشرز باللوحة الرئيسية',
    category: 'الكهرباء والإنارة',
    categoryIcon: 'Zap',
    status: 'pending',
    description: 'يوجد صوت شرز متكرر عند تشغيل التكييف والقاطع الأوتوماتيكي يفصل باستمرار. مطلوب فني فوراً.',
    price: 220,
    createdAt: 'منذ 18 دقيقة',
    scheduledTime: 'طوارئ فوري (خلال 30 دقيقة)',
    location: {
      lat: 29.9620,
      lng: 31.2610,
      address: 'شارع 9، المعادي، القاهرة',
      city: 'القاهرة',
      district: 'المعادي',
      buildingNumber: '15',
      floor: '4',
      apartment: '8',
      landmark: 'أمام محطة مترو المعادي',
    },
    offersCount: 2,
    isUrgent: true,
    clientName: 'سارة عبد الرحمن',
    clientPhone: '01055566677',
  },
  {
    id: 'task-105',
    title: 'تسريب مياه مفاجئ في ماسورة الصرف تحت المطبخ',
    category: 'السباكة والأدوات الصحية',
    categoryIcon: 'Wrench',
    status: 'pending',
    description: 'ماسورة الصرف تفرغ مياه على الأرض ومحبس الزاوية الرئيسي تالف ولا يغلق. مطلوب كشف وإصلاح عاجل.',
    price: 190,
    createdAt: 'منذ 35 دقيقة',
    scheduledTime: 'طوارئ فوري',
    location: {
      lat: 29.9570,
      lng: 31.2520,
      address: 'شارع اللاسلكي، المعادي الجديدة، القاهرة',
      city: 'القاهرة',
      district: 'المعادي',
      buildingNumber: '28',
      floor: '1',
      apartment: '2',
      landmark: 'بجوار مطعم مؤمن',
    },
    offersCount: 1,
    isUrgent: true,
    clientName: 'طارق الدسوقي',
    clientPhone: '01199887766',
  },
];

export const INITIAL_SERVICE_AREAS: ServiceArea[] = [
  { id: 'area-1', name: 'المعادي - شارع النصر', city: 'القاهرة', district: 'المعادي', lat: 29.9602, lng: 31.2569, active: true },
  { id: 'area-2', name: 'التجمع الخامس - شارع التسعين', city: 'القاهرة الجديدة', district: 'التجمع الخامس', lat: 30.0131, lng: 31.4293, active: true },
  { id: 'area-3', name: 'مدينة نصر - عباس العقاد', city: 'القاهرة', district: 'مدينة نصر', lat: 30.0561, lng: 31.3411, active: true },
  { id: 'area-4', name: 'مصر الجديدة - الكوربة', city: 'القاهرة', district: 'مصر الجديدة', lat: 30.0903, lng: 31.3256, active: true },
  { id: 'area-5', name: 'المهندسين - شارع جامعة الدول', city: 'الجيزة', district: 'المهندسين', lat: 30.0526, lng: 31.2001, active: true },
  { id: 'area-6', name: 'الدقي - ميدان المساحة', city: 'الجيزة', district: 'الدقي', lat: 30.0384, lng: 31.2124, active: true },
  { id: 'area-7', name: 'الشيخ زايد - هايبر وان', city: 'الجيزة', district: 'الشيخ زايد', lat: 30.0535, lng: 30.9818, active: true },
  { id: 'area-8', name: 'سموحة - الإسكندرية', city: 'الإسكندرية', district: 'سموحة', lat: 31.2156, lng: 29.9553, active: true },
  { id: 'area-9', name: 'الشروق - مدينتي', city: 'القاهرة الجديدة', district: 'مدينتي', lat: 30.1245, lng: 31.6421, active: true },
  { id: 'area-10', name: 'أكتوبر - ميدان الحصري', city: 'الجيزة', district: '6 أكتوبر', lat: 29.9722, lng: 30.9431, active: true },
];

export const DEFAULT_SYSTEM_CONFIG = {
  appName: 'فى الخدمة',
  supportPhone: '01012345678',
  commissionPercentage: 10,
  clientFreeRequestsCount: 3,
  techContactPointsCost: 5,
  allowEmergencyOrders: true,
};

